### ISSUE TITLE
Mouse Control — Unit Testing

### ISSUE THREAD

**Issue by Mark-Phillipson** [Mark-Phillipson/ProgrammingDictationBox#2]
In order to test the mouse control class, need to separate the commandline arguments from the class, and then supply them in the class constructor from program.CS.  Then the test methods can call the class with various arguments

**Comment by drake1011** [comment]
I'll take this one

**Comment by drake1011** [comment]
**PR** Created #9

**Comment by Mark-Phillipson** [comment]
Decided that MouseControl Class is not a very good class to test as it doesn't return anything it just controls the mouse.
